# Generated by Django 5.1.3 on 2024-12-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
