# Generated by Django 5.1.3 on 2024-12-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_remove_cartitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
