# Generated by Django 5.1.3 on 2024-12-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
