# Generated by Django 5.1.3 on 2024-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_alter_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
