# Generated by Django 5.1.3 on 2024-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_orderitem_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
