# Generated by Django 5.1.3 on 2024-12-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_remove_orderitem_discount_cartitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
    ]
