# Generated by Django 5.1.3 on 2024-12-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_alter_cartitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
