# Generated by Django 5.1.3 on 2024-12-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_order_discount_percentage_order_tax_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_percentage',
        ),
    ]
