# Generated by Django 5.1.3 on 2024-12-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_rename_expiry_date_coupon_validity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
