# Generated by Django 5.0.7 on 2025-01-24 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0038_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='price',
            new_name='actual_price',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
      
    ]
