# Generated by Django 5.0.7 on 2025-01-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0040_remove_variant_size_remove_variant_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
        model_name='orderitem',
        name='variant_size',
        field=models.ForeignKey(
        to='admin_app.VariantSize',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    ),
),
    ]
