# Generated by Django 5.0.7 on 2025-01-20 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_alter_order_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='stock',
        ),
        migrations.CreateModel(
            name='VariantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='admin_app.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='admin_app.variantsize')),
            ],
        ),
    ]
