# Generated by Django 5.0.7 on 2025-01-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_orderitem_variant_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='stock',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_size',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.variantsize'),
        ),
    ]