# Generated by Django 5.0.7 on 2025-01-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0042_remove_variant_price_remove_variant_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
