# Generated by Django 5.0.7 on 2025-01-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0043_variant_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
