# Generated by Django 5.0.7 on 2025-01-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0044_alter_variant_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
