# Generated by Django 5.1.3 on 2024-11-09 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='Anonymous', max_length=15)),
                ('lastname', models.CharField(default='Anonymous', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='0000000000', max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
