# Generated by Django 5.1.3 on 2024-11-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
