# Generated by Django 5.1.3 on 2024-11-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userdetails_groups_userdetails_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
