# Generated by Django 5.1.3 on 2024-12-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_address_is_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
