# Generated by Django 5.0.7 on 2025-01-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0038_remove_order_status_orderitem_status'),
        ('user_app', '0013_alter_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'variant')},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted', to='admin_app.variant'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
    ]
