# Generated by Django 5.0.7 on 2025-01-29 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0042_remove_variant_size_remove_variant_stock_and_more'),
        ('user_app', '0016_alter_wishlist_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted', to='admin_app.variant'),
        ),
    ]
